AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  EC2DescribeAllInstances

  Sample SAM Template for EC2DescribeAllInstances
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  EC2DescribeFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: describe-allinstances/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Policies:
        - EC2DescribePolicy: {}
      Events:
        DescribeAllInstances:
          Type: Schedule
          Properties:
            Schedule: cron(00 17 * * ? *)

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  EC2DescribeFunction:
    Description: "Describe all instances Lambda Function ARN"
    Value: !GetAtt EC2DescribeFunction.Arn
  EC2DescribeFunctionRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt EC2DescribeFunctionRole.Arn
